---
- name: Hello World Playbook
  hosts: localhost
  become: yes
  tasks:
    - name: Create file on kiosk
      file:
        path: /home/kiosk/hii_sumit
        state: directory
        mode: '755'
